name: velocity-smartmotd

services:
  proxy:
    image: docker.io/itzg/mc-proxy:2026.8.0
    restart: no
    user: ${CUID:-0}:${CGID:-0}
    environment:
      UID: 12321 # workaround for rootless docker setup
      GID: "${CGID:-0}"
      TYPE: velocity
    ports:
      - "25565:25565/tcp"
    volumes:
      - ./proxy/data:/server
      - ./proxy/config:/config
      - ../target/velocity-smartmotd-1.0-SNAPSHOT.jar:/plugins/velocity-smartmotd-1.0-SNAPSHOT.jar:ro
    depends_on:
      - server
  server:
    image: docker.io/itzg/minecraft-server:2026.8.1
    hostname: server
    restart: no
    user: ${CUID:-0}:${CGID:-0}
    environment:
      UID: "${CUID:-0}"
      GID: "${CGID:-0}"
      TYPE: paper
      EULA: TRUE
      ONLINE_MODE: FALSE
    volumes:
      - ./server/data:/data
      - ./server/config:/config