name: Create Release Draft
on: workflow_dispatch
jobs:
  package:
    uses: ./.github/workflows/package.yml

  create_release_draft:
    needs: [ package ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4
      - name: "Print Artifacts (Debug only)"
        if: runner.debug == '1'
        run: |
          tree
      - name: "Get Version"
        id: get_version
        run: echo "version=$(grep -m 1 -oP '(?<=<version>).*?(?=</version>)' pom.xml)" >> "$GITHUB_OUTPUT"
      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ steps.get_version.outputs.version }}"
          tag_name: "v${{ steps.get_version.outputs.version }}"
          body: "TODO: Write Changelog"
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: ./artifact/*.jar